const fs = require('fs');
const path = 'src/components/shared/WaitlistModal.tsx';
let content = fs.readFileSync(path, 'utf8');

const oldDescription = "{current === 'calendly' && (\r\n                      <div className=\"space-y-4\">\r\n                        <p className=\"text-white/80 text-sm leading-relaxed\">\r\n                          Choisissez un cr?neau pour ?changer avec l'?quipe Offstone. Sur ordinateur, l'agenda est affich? ? droite. Sur mobile, utilisez le bouton ci-dessous.\r\n                        </p>\r\n                        <div className=\"lg:hidden\">\r\n                          <button\r\n                            type=\"button\"\r\n                            onClick={() => setIsCalendarMobileOpen(true)}\r\n                            className=\"w-full px-4 py-3 rounded-xl bg-[#F7B096] text-black font-medium text-sm shadow-md hover:opacity-90 transition\"\r\n                          >\r\n                            Ouvrir le calendrier\r\n                          </button>\r\n                        </div>\r\n                        <div className=\"hidden lg:block rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/70\">\r\n                          S?lectionnez votre cr?neau dans le panneau ? droite.\r\n                        </div>\r\n                      </div>\r\n                    )}\r\n\r\n";
const newDescription = `{current === 'calendly' && (\r\n                      <div className="space-y-4">\r\n                        <p className="text-white/80 text-sm leading-relaxed">\r\n                          Choisissez un créneau pour échanger avec l'équipe Offstone. Sur ordinateur, l'agenda est affiché à droite. Sur mobile, utilisez le bouton ci-dessous.\r\n                        </p>\r\n                        <div className="lg:hidden">\r\n                          <button\r\n                            type="button"\r\n                            onClick={() => setIsCalendarMobileOpen(true)}\r\n                            className="w-full px-4 py-3 rounded-xl bg-[#F7B096] text-black font-medium text-sm shadow-md hover:opacity-90 transition"\r\n                          >\r\n                            Ouvrir le calendrier\r\n                          </button>\r\n                        </div>\r\n                        <div className="hidden lg:block rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/70">\r\n                          Sélectionnez votre créneau dans le panneau à droite.\r\n                        </div>\r\n                      </div>\r\n                    )}\r\n\r\n`;
if (!content.includes(oldDescription)) {
  throw new Error('Description block not found');
}
content = content.replace(oldDescription, newDescription);

const oldOverlay = "              {current === 'calendly' && isCalendarMobileOpen && (\r\n                <div className=\"lg:hidden absolute left-0 right-0 top-0 bottom-36 z-20 flex flex-col bg-black/95 backdrop-blur-sm px-4 py-5\">\r\n                  <div className=\"flex items-center justify-between mb-4\">\r\n                    <h5 className=\"text-base font-medium text-white\">Planifier un rendez-vous</h5>\r\n                    <button type=\"button\" onClick={() => setIsCalendarMobileOpen(false)} className=\"p-2 rounded-full bg-white/10 text-white hover:bg-white/20\" aria-label=\"Fermer le calendrier\">\r\n                      <CloseIcon />\r\n                    </button>\r\n                  </div>\r\n                  <div className=\"flex-1 overflow-hidden rounded-xl border border-white/10 bg-white\">\r\n                    <div className=\"meetings-iframe-container h-full w-full\" data-src={HUBSPOT_MEETING_URL}></div>\r\n                  </div>\r\n                </div>\r\n              )}\r\n\r\n";
const newOverlay = `              {current === 'calendly' && isCalendarMobileOpen && (\r\n                <div className="lg:hidden absolute left-0 right-0 top-0 bottom-36 z-20 flex flex-col bg-black/95 backdrop-blur-sm px-4 py-5">\r\n                  <div className="flex items-center justify-between mb-4">\r\n                    <h5 className="text-base font-medium text-white">Planifier un rendez-vous</h5>\r\n                    <button type="button" onClick={() => setIsCalendarMobileOpen(false)} className="p-2 rounded-full bg-white/10 text-white hover:bg-white/20" aria-label="Fermer le calendrier">\r\n                      <CloseIcon />\r\n                    </button>\r\n                  </div>\r\n                  <div className="flex-1 overflow-hidden rounded-xl border border-white/10 bg-white">\r\n                    <iframe\r\n                      src={HUBSPOT_MEETING_URL}\r\n                      title="Planifier un rendez-vous Offstone"\r\n                      className="h-full w-full border-0"\r\n                      allow="fullscreen"\r\n                      loading="lazy"\r\n                    />\r\n                  </div>\r\n                </div>\r\n              )}\r\n\r\n`;
if (!content.includes(oldOverlay)) {
  throw new Error('Overlay block not found');
}
content = content.replace(oldOverlay, newOverlay);

const oldDesktop = "            {twoCols && (\r\n              <div className=\"hidden lg:flex flex-col h-full\">\r\n                <div className=\"w-full h-[560px] rounded-xl border border-white/10 bg-white overflow-hidden shadow-inner\">\r\n                  <div className=\"meetings-iframe-container h-full w-full\" data-src={HUBSPOT_MEETING_URL}></div>\r\n                </div>\r\n                <p className=\"mt-3 text-xs text-white/60\">Choisissez directement votre cr?neau ci-dessus sans quitter le formulaire.</p>\r\n              </div>\r\n            )}\r\n          </div>\r\n";
const newDesktop = `            {twoCols && (\r\n              <div className="hidden lg:flex flex-col h-full">\r\n                <div className="w-full h-[560px] rounded-xl border border-white/10 bg-white overflow-hidden shadow-inner">\r\n                  <iframe\r\n                    src={HUBSPOT_MEETING_URL}\r\n                    title="Planifier un rendez-vous Offstone"\r\n                    className="h-full w-full border-0"\r\n                    allow="fullscreen"\r\n                    loading="lazy"\r\n                  />\r\n                </div>\r\n                <p className="mt-3 text-xs text-white/60">Choisissez directement votre créneau ci-dessus sans quitter le formulaire.</p>\r\n              </div>\r\n            )}\r\n          </div>\r\n`;
if (!content.includes(oldDesktop)) {
  throw new Error('Desktop block not found');
}
content = content.replace(oldDesktop, newDesktop);

fs.writeFileSync(path, content, 'utf8');
